image: Visual Studio 2017

environment:
  nodejs_version: "8.9.4"

platform:
  - x64

install:
  - ps: echo 'INSTALL START'
  - ps: Install-Product node $env:nodejs_version
  - cd ./src/
  - ls 
  - npm install --verbose

test_script:
  - node --version
  - npm -- version
  - npm run test
  - npm run build
  - ps: echo 'done test'

shallow_clone: true

build: off

cache:
  node_modules -> package-lock.json